from .PlotHistoryWidget import PlotHistoryWidget
from .SelectCallbacksWidget import SelectCallbackWidget
from .SelectLossesWidget import SelectLossesWidget
from .SelectMetricsWidget import SelectMetricsWidget
from .SelectModelColumnsWidget import SelectModelColumnsWidget
from .SelectOptimizerWidget import SelectOptimizerWidget
from .TrainModelWidget import TrainModelWidget
