from .DataStatWidget import DataStatWidget
from .DataGridWidget import DataGridWidget
from .DataPlotWidget import DataPlotWidget
from .SelectInputColumnsWidget import SelectInputColumnsWidget
from .SelectOutputColumnsWidget import SelectOutputColumnsWidget
from .SplitDataWidget import SplitDataWidget
