from .SelectLossesWidget import SelectLossesWidget
from .SelectMetricsWidget import SelectMetricsWidget
from .SelectOptimizerWidget import SelectOptimizerWidget
from .TrainingDataWidget import TrainingDataWidget
