from .SelectCallbacksWidget import SelectCallbackWidget
from .SelectLossesWidget import SelectLossesWidget
from .SelectMetricsWidget import SelectMetricsWidget
from .SelectOptimizerWidget import SelectOptimizerWidget
from .SelectTrainingDataWidget import SelectTrainingDataWidget
